### ISSUE TITLE
Go through the EMNLP format. Call for Main Conference Papers - EMNLP 2024

### ISSUE THREAD

**Issue by Adamliu1** [Adamliu1/SNLP_GCW#84] opened 2024-06-01 23:41 UTC
Migrated from google doc

**Comment by Willmish** [comment] 2024-06-05 01:17
Some notes for EMNLP submission:

-   for 2024 EMNLP uses **only** ACL Rolling Review (ARR), submission deadline: 15th June, 11:59 PM anywhere on Earth <https://openreview.net/group?id=aclweb.org/ACL/ARR/2024/June#tab-your-consoles>
-   **AS OF April 1st:** Mandatory reviewing workload: we will need to dedicate someone (or a bunch of us) to review at least 3 papers during the reviewing cycle **each**. <https://aclrollingreview.org/reviewing-workload-requirement/>
-   Submission topics: Definitely need to review this together (potentially see what papers were on what tracks in prev years), however some do stand out, as we propose a **data efficient** method for **task unlearning**:
    -   the main theme - Efficiency in Model Algorithms, Training, and Inference (speaks for itself, but there is a summary on the website)
    -   Low-resource Methods for NLP
    -   Ethics, Bias, and Fairness (potentially, since harmfulness unlearning is a part of it)
    -   Information Extraction (in our case task efficiency decrease/removal)
    -   Question Answering (one of the tasks unlearned - harmful question answering)
-   Two stage review: 1st submit to ARR, then commit to EMNLP 2024 - they make the final decision. Commitment deadline: 20th August 2024.
-   Other important dates:
    -   Notification of acceptance: 20th September 2024
    -   Camera-ready papers due: 3rd October 2024
    -   Main Conference 12-14th November 2024
    -   Workshops + Tutorials: 15th-16th November 2024
-   To decide: Long (8 pages) vs short (4 pages) paper: <https://aclrollingreview.org/cfp#long-papers> (probably long, as we want to include quite a bit of concrete evaluation and analysis)
-   Two-Way anonymised review: can't reveal names or affiliation in submission (including self references "X showed in .." vs "We previously showed in.."). **Supplementary material** (read: GH repo) should also be anonymised: <https://anonymous.4open.science/>
-   Citations: We are not required to make detailed comparisons/experiments regarding papers published less than 3 months before submission deadline (but can reference) <https://aclrollingreview.org/cfp#citation-and-comparison>
-   Multiple submission policy: - DON'T DO IT <https://aclrollingreview.org/cfp#multiple-submission-policy>
-   Ethics policy:  authors encouraged to include ethical impact of the work (however not required), will be taken into account in the review process <https://aclrollingreview.org/cfp#ethics-policy>
-   AI writing assistance: disclose if used a lot, disclose in README if used for code writing assitance
-   Limitations: **REQUIRED SECTION,** at the end of the paper, does **NOT** count towards page limit. (desk rejected without it). <https://aclrollingreview.org/cfp#limitations-required-section>
-   Submission template: ACL style: <https://aclrollingreview.org/cfp#paper-submission-and-templates>
-   Optional supplementary materials (appendix, software, data): encouraged to improve reproducibility of results, software submitted as a single .tgz or .zip archive, data in a separate .tgz or .zip archive. Material MUST BE FULLY ANONYMISED! <https://aclrollingreview.org/cfp#optional-supplementary-materials-appendices-software-and-data>
-   FINAL VERSION: given 1 additional page of content, to address reviewers' comments (9 pages for long total), assuming that means we submit with 8, only expand to 9 to address comments
-   PResentation: if accepted ,someone need s to present in person or virtually otherwise it will be rejected

Enjoy the tl;dr, I tried to capture it all (handwritten), but defo worth another glance @Adamliu1

**Comment by TheRootOf3** [comment] 2024-07-01 14:09
Closing as not submitting to EMNLP.

**Closed by TheRootOf3** 2024-07-01 14:09 UTC
Labels: review
